## 1. 파이썬 파일 처리

In [16]:
sample_file = 'sample.txt'

In [17]:
# 파일을 open하여 내용 출력
with open(sample_file, mode='r', encoding='utf-8') as f:
    content = f.read()
    print(content)

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [18]:
# 파일을 open하고 한 줄씩 출력하기
with open(sample_file, mode='r', encoding='utf-8') as f:
    line = f.readline()

    while line:
        print(line, end='')
        line = f.readline()

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [19]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며, 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, mode='r', encoding='utf-8') as f:
    for line in f:
        print(line, end='')

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [20]:
# 여러 개의 파일 읽기
import glob

files = glob.glob('data/*.txt')

for file_name in files:
    print(f'[{file_name}]')

    with open(file_name, mode='r', encoding='utf-8') as f:
        print(f.read())

## 2. 파이썬 문자열 다루기

In [21]:
### 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "

print(b1)
print(b1.strip())

 작은 일에 성실한 사람은      큰일에도 성실하고
작은 일에 성실한 사람은      큰일에도 성실하고

In [22]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."

print(text.lstrip('.'))
print(text.rstrip('.'))
print(text.strip('.'))

작은 일에 성실한 사람은, 큰일에도 성실하고....
....작은 일에 성실한 사람은, 큰일에도 성실하고
작은 일에 성실한 사람은, 큰일에도 성실하고

In [23]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."

result = text.split(',')
print(result)

# 분리 후 각 문자열의 양쪽 '.'과 공백 제거
result = [item.strip().strip('.') for item in result]
print(result)

['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']
['작은 일에 성실한 사람은', '큰일에도 성실하고']

In [ ]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"

result = numbers.split('.')
print(result)

# 공백 제거 후 빈 문자열 제외
result = [item.strip() for item in result if item.strip()]
print(result)

## 3. 판다스로 데이터 가져오기

In [24]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [25]:
# 타이타닉 데이터 가져오기
import pandas as pd

titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

titanic_df = pd.read_csv(titanic_data)
titanic_df

                        PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
1\t0\t3\tBraund           Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2\t1\t1\tCumings          Mrs. John Bradley (Florence Briggs Thayer)\tf...
3\t1\t3\tHeikkinen        Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4\t1\t1\tFutrelle         Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
5\t0\t3\tAllen            Mr. William Henry\tmale\t35\t0\t0\t373450\t8....
...                                                                    ...
152\t1\t1\tPears          Mrs. Thomas (Edith Wearne)\tfemale\t22\t1\t0\...
153\t0\t3\tMeo            Mr. Alfonzo\tmale\t55.5\t0\t0\tA.5. 11206\t8....
154\t0\t3\tvan Billiard   Mr. Austin Blyler\tmale\t40.5\t0\t2\tA/5. 851...
155\t0\t3\tOlsen          Mr. Ole Martin\tmale\t\t0\t0\tFa 265302\t7.31...
156\t0\t1\tWilliams       Mr. Charles Duane\tmale\t51\t0\t1\tPC 17597\t...

[156 rows x 1 columns]

In [26]:
# 탭을 기준으로 분리하여 읽기
# 탭으로 구분된 파일을 읽을 때는 sep='\t' 사용
# 예: tab_df = pd.read_csv('data/sample.tsv', sep='\t')

# 타이타닉 CSV에 sep='\t'를 적용하면 한 줄 전체가 하나의 열로 읽히므로
# 구분자 사용 방법을 확인하는 예제로 실행
titanic_tab = pd.read_csv(titanic_data, sep='\t')
titanic_tab.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [27]:
# 앞부분 확인
titanic_df.head()

                   PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
1\t0\t3\tBraund      Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2\t1\t1\tCumings     Mrs. John Bradley (Florence Briggs Thayer)\tf...
3\t1\t3\tHeikkinen   Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4\t1\t1\tFutrelle    Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
5\t0\t3\tAllen       Mr. William Henry\tmale\t35\t0\t0\t373450\t8....

In [28]:
# 뒷부분 확인
titanic_df.tail()

                        PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
152\t1\t1\tPears          Mrs. Thomas (Edith Wearne)\tfemale\t22\t1\t0\...
153\t0\t3\tMeo            Mr. Alfonzo\tmale\t55.5\t0\t0\tA.5. 11206\t8....
154\t0\t3\tvan Billiard   Mr. Austin Blyler\tmale\t40.5\t0\t2\tA/5. 851...
155\t0\t3\tOlsen          Mr. Ole Martin\tmale\t\t0\t0\tFa 265302\t7.31...
156\t0\t1\tWilliams       Mr. Charles Duane\tmale\t51\t0\t1\tPC 17597\t...

In [34]:
# 데이터 개수/형태 확인
print('shape :', titanic_df.shape)
print('행 개수 :', len(titanic_df))
print('열 개수 :', len(titanic_df.columns))

shape : (156, 1)
행 개수 : 156
열 개수 : 1

In [30]:
# 데이터의 기본 통계치 보기
titanic_df.describe()

       PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
count                                                 156
unique                                                156
top      Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
freq                                                    1

In [31]:
# 데이터 구성 정보 확인하기
titanic_df.info()

<class 'pandas.DataFrame'>
Index: 156 entries, 1	0	3	Braund to 156	0	1	Williams
Data columns (total 1 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   PassengerId	Survived	Pclass	Name	Sex	Age	SibSp	Parch	Ticket	Fare	Cabin	Embarked  156 non-null    str
dtypes: str(1)
memory usage: 2.4+ KB

In [ ]:
# 열 이름 변경하기 : 모두 소문자로 변경
new_columns = []
for col in titanic_df.columns:
    new_columns.append(col.lower())

titanic_df.columns = new_columns
titanic_df.head

Index(['passengerid\tsurvived\tpclass\tname\tsex\tage\tsibsp\tparch\tticket\tfare\tcabin\tembarked'], dtype='str')

                   passengerid\tsurvived\tpclass\tname\tsex\tage\tsibsp\tparch\tticket\tfare\tcabin\tembarked
1\t0\t3\tBraund      Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2\t1\t1\tCumings     Mrs. John Bradley (Florence Briggs Thayer)\tf...
3\t1\t3\tHeikkinen   Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4\t1\t1\tFutrelle    Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
5\t0\t3\tAllen       Mr. William Henry\tmale\t35\t0\t0\t373450\t8....

In [33]:
# 데이터프레임 복사하기
titanic_copy = titanic_df.copy()

print(titanic_copy.shape)
titanic_copy.head()

(156, 1)

                   passengerid\tsurvived\tpclass\tname\tsex\tage\tsibsp\tparch\tticket\tfare\tcabin\tembarked
1\t0\t3\tBraund      Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2\t1\t1\tCumings     Mrs. John Bradley (Florence Briggs Thayer)\tf...
3\t1\t3\tHeikkinen   Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4\t1\t1\tFutrelle    Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
5\t0\t3\tAllen       Mr. William Henry\tmale\t35\t0\t0\t373450\t8....