## 결측치

In [2]:
import pandas as pd

# 타이타닉 데이터가 저장된 주소
url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

# 데이터를 DataFrame으로 불러오기
titanic_df = pd.read_csv(url, sep='\t')

# 데이터 구조, 자료형, 결측치 개수 확인
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [28]:
# 사용할 컬럼 이름 지정
new_columns = ['passengerId', 'survived', 'pclass', 'name','sex', 'age', 'sibsp', 'parch','ticket', 'fare', 'cabin', 'embarked']
# 기존 컬럼 이름을 새 이름으로 변경
titanic_df.columns = new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [30]:
# age가 결측치(NaN)인 데이터만 추출
titanic_df['age'][titanic_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [31]:
# age 열의 각 값이 결측치인지 확인
titanic_df['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [32]:
# age가 결측치인 값만 출력
titanic_df['age'][titanic_df['age'].isnull()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [34]:
# age 열의 결측치 개수 확인
titanic_df['age'].isnull().sum()

np.int64(30)

In [16]:
# age 값이 존재하는지 확인
titanic_df['Age'].notnull()

0       True
1       True
2       True
3       True
4       True
       ...
151     True
152     True
153     True
154    False
155     True
Name: Age, Length: 156, dtype: bool

In [35]:
# age가 정상적으로 존재하는 데이터만 추출
titanic_df['age'][titanic_df['age'].notnull()]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
150    51.0
151    22.0
152    55.5
153    40.5
155    51.0
Name: age, Length: 126, dtype: float64

In [36]:
# age가 결측치가 아닌 행에서 age, name 열만 추출
titanic_df.loc[titanic_df['age'].notnull(),['age', 'name']]

      age                                               name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
150  51.0                         Bateman, Rev. Robert James
151  22.0                  Pears, Mrs. Thomas (Edith Wearne)
152  55.5                                   Meo, Mr. Alfonzo
153  40.5                    van Billiard, Mr. Austin Blyler
155  51.0                        Williams, Mr. Charles Duane

[126 rows x 2 columns]

In [21]:
# age가 결측치인 사람의 age와 name 출력
titanic_df.loc[titanic_df['Age'].isnull(),['Age', 'Name']]

     Age                                            Name
5    NaN                                Moran, Mr. James
17   NaN                    Williams, Mr. Charles Eugene
19   NaN                         Masselmani, Mrs. Fatima
26   NaN                         Emir, Mr. Farred Chehab
28   NaN                   O'Dwyer, Miss. Ellen "Nellie"
29   NaN                             Todoroff, Mr. Lalio
31   NaN  Spencer, Mrs. William Augustus (Marie Eugenie)
32   NaN                        Glynn, Miss. Mary Agatha
36   NaN                                Mamee, Mr. Hanna
42   NaN                             Kraeff, Mr. Theodor
45   NaN                        Rogers, Mr. William John
46   NaN                               Lennon, Mr. Denis
47   NaN                       O'Driscoll, Miss. Bridget
48   NaN                             Samaan, Mr. Youssef
55   NaN                               Woolner, Mr. Hugh
64   NaN                           Stewart, Mr. Albert A
65   NaN                        Moubarek, Master. Gerios
76   NaN                               Staneff, Mr. Ivan
77   NaN                        Moutal, Mr. Rahamin Haim
82   NaN                  McDermott, Miss. Brigdet Delia
87   NaN                   Slocovski, Mr. Selman Francis
95   NaN                     Shorney, Mr. Charles Joseph
101  NaN                Petroff, Mr. Pastcho ("Pentcho")
107  NaN                          Moss, Mr. Albert Johan
109  NaN                             Moran, Miss. Bertha
121  NaN                      Moore, Mr. Leonard Charles
126  NaN                             McMahon, Mr. Martin
128  NaN                               Peter, Miss. Anna
140  NaN                   Boulos, Mrs. Joseph (Sultana)
154  NaN                           Olsen, Mr. Ole Martin

In [22]:
# 데이터 앞 5개 확인
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
# cabin의 NaN 값을 'N'으로 채우기
titanic_df['cabin'] = titanic_df['cabin'].fillna('N')

# 변경 결과 확인
titanic_df['cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
151      C2
152       N
153       N
154       N
155       N
Name: cabin, Length: 156, dtype: str

In [38]:
# cabin에 각 값이 몇 개 있는지 확인
titanic_df['cabin'].value_counts()

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [39]:
# 0번 행의 cabin 값 확인
titanic_df['cabin'][0]

'N'

In [40]:
# cabin 값에서 첫 번째 문자만 추출
titanic_df['cabin'] = titanic_df['cabin'].apply(lambda x: x[0])

# 결과 확인
titanic_df['cabin']

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: cabin, Length: 156, dtype: str

In [41]:
# 전체 데이터 구조와 결측치 상태 확인
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   survived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        156 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [42]:
# 원본 DataFrame을 별도의 DataFrame으로 깊은 복사
copy_titanic_df = titanic_df.copy()

# 복사 결과 확인
copy_titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [44]:
# 원본 DataFrame의 메모리 주소
hex(id(titanic_df))

'0x25951ef45f0'

In [45]:
# 복사본 DataFrame의 메모리 주소
hex(id(copy_titanic_df))

'0x25952cab980'

In [46]:
# 원본 확인
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [47]:
# 복사본 확인
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [48]:
# 복사본의 age 값을 모두 0으로 변경
copy_titanic_df['age'] = 0

# 복사본 확인
copy_titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,0,373450,8.0500,N,S

In [49]:
# 원본은 변경되지 않았는지 확인
titanic_df.head()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

## 통계 함수

In [52]:
# 숫자형 열의 주요 통계값을 한 번에 확인
titanic_df.describe()

,passengerId,survived,pclass,age,sibsp,parch,fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [53]:
# 각 열의 값들을 모두 더함
titanic_df.sum()

passengerId                                                12246
survived                                                      54
pclass                                                       378
name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
sex            malefemalefemalefemalemalemalemalemalefemalefe...
age                                                      3545.83
sibsp                                                         96
parch                                                         62
ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
fare                                                   4385.0956
cabin          NCNCNNENNNGCNNNNNNNNNDNANNNCNNNBNNNNNNNNNNNNNN...
embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object

In [54]:
# 각 열에서 NaN이 아닌 데이터 개수 확인
titanic_df.count()

passengerId    156
survived       156
pclass         156
name           156
sex            156
age            126
sibsp          156
parch          156
ticket         156
fare           156
cabin          156
embarked       155
dtype: int64

In [55]:
# 각 열의 최댓값 확인
titanic_df.max()

passengerId                                156
survived                                     1
pclass                                       3
name           van Billiard, Mr. Austin Blyler
sex                                       male
age                                       71.0
sibsp                                        5
parch                                        5
ticket                             W.E.P. 5734
fare                                     263.0
cabin                                        N
embarked                                     S
dtype: object

In [56]:
# 각 열의 최솟값 확인
titanic_df.min()

passengerId                                                 1
survived                                                    0
pclass                                                      1
name           Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
sex                                                    female
age                                                      0.83
sibsp                                                       0
parch                                                       0
ticket                                                 110465
fare                                                     6.75
cabin                                                       A
embarked                                                    C
dtype: object

In [62]:
# 숫자형 열의 평균값 구하기
# age 열은 숫자형이므로 정상 실행
titanic_df['age'].mean()

np.float64(28.141507936507935)

In [59]:
# 숫자형 열의 중앙값 구하기
titanic_df.median(numeric_only=True)

passengerId    78.5000
survived        0.0000
pclass          3.0000
age            26.0000
sibsp           0.0000
parch           0.0000
fare           14.4542
dtype: float64

In [60]:
# 각 열에서 가장 많이 등장한 값 구하기
titanic_df.mode()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0.0,3.0,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",male,21.0,0.0,0.0,113803,8.05,N,S
1,2,NaN,NaN,"Allen, Mr. William Henry",NaN,NaN,NaN,NaN,11668,NaN,NaN,NaN
2,3,NaN,NaN,"Andersson, Miss. Ellis Anna Maria",NaN,NaN,NaN,NaN,19950,NaN,NaN,NaN
3,4,NaN,NaN,"Andersson, Miss. Erna Alexandra",NaN,NaN,NaN,NaN,237736,NaN,NaN,NaN
4,5,NaN,NaN,"Andersson, Mr. Anders Johan",NaN,NaN,NaN,NaN,2651,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,NaN,NaN,"Williams, Mr. Charles Duane",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,153,NaN,NaN,"Williams, Mr. Charles Eugene",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,154,NaN,NaN,"Woolner, Mr. Hugh",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,155,NaN,NaN,"Zabour, Miss. Hileni",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,156,NaN,NaN,"van Billiard, Mr. Austin Blyler",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
# 평균 절대 편차 구하기
# age 열의 평균 절대 편차
(titanic_df['age'] - titanic_df['age'].mean()).abs().mean()

np.float64(11.142858402620307)

In [67]:
# 숫자형 열의 분산 구하기
titanic_df.var(numeric_only=True)

passengerId    2041.000000
survived          0.227792
pclass            0.632754
age             213.565487
sibsp             1.115633
parch             0.757155
fare           1552.442481
dtype: float64

In [68]:
# 숫자형 열의 표준편차 구하기
titanic_df.std(numeric_only=True)

passengerId    45.177428
survived        0.477275
pclass          0.795459
age            14.613880
sibsp           1.056235
parch           0.870146
fare           39.401047
dtype: float64

In [69]:
# 숫자형 열의 왜도 구하기
titanic_df.skew(numeric_only=True)

passengerId    0.000000
survived       0.653058
pclass        -0.912744
age            0.700367
sibsp          2.220685
parch          2.760421
fare           4.176408
dtype: float64

In [70]:
# 숫자형 열의 첨도 구하기
titanic_df.kurt(numeric_only=True)

passengerId    -1.200000
survived       -1.594120
pclass         -0.803872
age             0.613747
sibsp           4.996881
parch           9.346662
fare           21.109985
dtype: float64

In [71]:
# age의 최댓값
titanic_df['age'].max()

np.float64(71.0)

In [72]:
# 기본 통계 요약
titanic_df.describe()

# 각 열의 합계
titanic_df.sum()

# NaN을 제외한 데이터 개수
titanic_df.count()

# 최댓값
titanic_df.max()

# 최솟값
titanic_df.min()

# 숫자형 열의 평균
titanic_df.mean(numeric_only=True)

# 숫자형 열의 중앙값
titanic_df.median(numeric_only=True)

# 최빈값
titanic_df.mode()

# 분산
titanic_df.var(numeric_only=True)

# 표준편차
titanic_df.std(numeric_only=True)

# 왜도
titanic_df.skew(numeric_only=True)

# 첨도
titanic_df.kurt(numeric_only=True)

passengerId    -1.200000
survived       -1.594120
pclass         -0.803872
age             0.613747
sibsp           4.996881
parch           9.346662
fare           21.109985
dtype: float64